def find_costs(i,a,b,c,d,f,g):
    x_1 = 0
    x_2 = 0
    x_3 = 0
    x_4 = 0
    x_5 = 0
    x_6 = 0
    x_7 = 0
    x_8 = 0
    if i==1:
        x_5=(a)/(1+b)
        x_8=b*x_5
    elif i==2:
        x_7=a/((d/b)+d)
        x_8=d*x_7
        x_5=a-(x_7*(1+d))
        # print(f'm_сум = {a} = {x_5+x_7+x_8}')
        # print(f'k_m = {b} = {x_8/(x_5+x_7)}')
        # print(f'k_m_огг= {d} = {x_8/x_7}')
    elif i==3:
        x_5=a/(1+b)
        x_8=x_5*(b-c)
        x_6=c*x_5
        # print(f'm_сум = {a} = {x_5 + x_6 + x_8}')
        # print(f'k_m = {b} = {(x_6 +x_8) / (x_5)}')
        # print(f'k_m_вгг= {c} = {x_6 / x_5}')
    elif i==4:
        x_7=a/(((b-d)/(c-b))*(1+c)+1+d)
        x_5=(a-x_7*(1+d))/(1+c)
        x_6=c*x_5
        x_8=d*x_7
        # print(f'm_сум = {a} = {x_5 + x_6 + x_7+ x_8}')
        # print(f'k_m = {b} = {(x_6 + x_8) / (x_5+x_7)}')
        # print(f'k_m_вгг= {c} = {x_6 / x_5}')
        # print(f'k_m_огг= {d} = {x_8 / x_7}')
    elif i==5:
        x_1=a*f
        x_5=a*(1 - f)/(1 + b)
        x_8=a*b*(1 - f)/(1 + b)
        # print(f'm_сум = {a} = {x_1+x_5+x_8}')
        # print(f'k_m = {b} = {(x_8)/(x_5)}')
        # print(f'n%= {f} = {(x_1)/(x_1+x_5+x_8)}')
    elif i==6:
        x_1=a*f
        x_5=a*(d - b + b*f - d*f)/(d*(1 + b))
        x_7=a*b*(1 - f)/(d*(1 + b))
        x_8=a*b*(1 - f)/(1 + b)
        print(f'm_сум = {a} = {x_1 + x_5 + x_7+x_8}')
        print(f'k_m = {b} = {(x_8) / (x_5+x_7)}')
        print(f'k_m_огг= {d} = {x_8 / x_7}')
        print(f'n%= {f} = {(x_1) / (x_1 + x_5 + x_7+x_8)}')
    elif i==7:
        x_1=a*f
        x_5=a*(1 - f)/(1 + b)
        x_6=a*c*(1 - f)/(1 + b)
        x_8=a*(b - c + c*f - b*f)/(1 + b)
        # print(f'm_сум = {a} = {x_1+x_5+x_6+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/(x_5)}')
        # print(f'k_m_вгг= {c} = {x_6/x_5}')
        # print(f'n%= {f} = {(x_1)/(x_1+x_5+x_6+x_8)}')
    elif i==8:
        x_1=a*f
        x_5=a*(b - d + d*f - b*f)/(c - d + b*c - b*d)
        x_6=a*c*(b - d + d*f - b*f)/(c - d + b*c - b*d)
        x_7=a*(c - b + b*f - c*f)/(c - d + b*c - b*d)
        x_8 =a*d*(c - b + b*f - c*f)/(c - d + b*c - b*d)
        # print(f'm_сум = {a} = {x_1+x_5+x_6+x_7+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/(x_5+x_7 )}')
        # print(f'k_m_вгг= {c} = {x_6/x_5 }')
        # print(f'k_m_огг= {d} = {x_8 / x_7}')
        # print(f'n%= {f} = {x_1/(x_1+x_5+x_6+x_7+x_8 )}')
    elif i==9:
        x_1=a*f/(1 + c)
        x_2=a*c*f/(1 + c)
        x_5=a*(1 - f)/(1 + b)
        x_8=a*b*(1 - f)/(1 + b)
        # print(f'm_сум = {a} = {x_1+x_2+x_5+x_8}')
        # print(f'k_m = {b} = {x_8/x_5 }')
        # print(f'k_m_вгг= {c} = {x_2/x_1 }')
        # print(f'n%= {f} = {(x_1+x_2)/(x_1+x_2+x_5+x_8 )}')
    elif i==10:
        x_1=a*f/(1 + c)
        x_2=a*c*f/(1 + c)
        x_5=a*(d - b + b*f - d*f)/(d*(1 + b))
        x_7=a*b*(1 - f)/(d*(1 + b))
        x_8 =a*b*(1 - f)/(1 + b)
        # print(f'm_сум = {a} = {x_1+x_2+x_5+x_7+x_8}')
        # print(f'k_m = {b} = {x_8/(x_5+x_7 )}')
        # print(f'k_m_вгг= {c} = {x_2/x_1 }')
        # print(f'k_m_огг= {d} = {x_8 / x_7}')
        # print(f'n%= {f} = {(x_1+x_2)/(x_1+x_2+x_5+x_7+x_8 )}')
    elif i==11:
        x_1=a*f/(1 + c)
        x_2=a*c*f/(1 + c)
        x_5=a*(1 - f)/(1 + b)
        x_6=a*c*(1 - f)/(1 + b)
        x_8=a*(b - c + c*f - b*f)/(1 + b)
        # print(f'm_сум = {a} = {x_1+x_2+x_5+x_6+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/x_5 }')
        # print(f'k_m_вгг= {c} = {x_6/x_5  }')
        # print(f'k_m_огг= {c} = {x_2/x_1}')
        # print(f'n%= {f} = {(x_1+x_2)/(x_1+x_2+x_5+x_6+x_8 )}')
    elif i==12:
        x_1=a*f/(c + 1.0)
        x_2=a*c*f/(c + 1.0)
        x_5=a*(-b*f + b + d*f - d)/(b*c - b*d + c - d)
        x_6=a*c*(-b*f + b + d*f - d)/(b*c - b*d + c - d)
        x_7=a*(b*f - b - c*f + c)/(b*c - b*d + c - d)
        x_8 =a*d*(b*f - b - c*f + c)/(b*c - b*d + c - d)
        # print(f'm_сум = {a} = {x_1+x_2+x_5+x_6+x_7+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/(x_5+x_7)}')
        # print(f'k_m_вгг= {c} = {x_6/x_5}')
        # print(f'k_m_вгг= {c} = {x_2/x_1}')
        # print(f'k_m_огг= {d} = {x_8 / x_7}')
        # print(f'n%= {f} = {(x_1+x_2)/(x_1+x_2+x_5+x_6+x_7+x_8 )}')
    elif i==13:
        x_1=a*f/(g + 1.0)
        x_4=a*f*g/(g + 1.0)
        x_5=a*(1.0 - f)/(b + 1.0)
        x_8=a*b*(1.0 - f)/(b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_4+x_5+x_8}')
        # print(f'k_m = {b} = {x_8/x_5}')
        # print(f'n%= {f} = {(x_1+x_4)/(x_1+x_4+x_5+x_8)}')
        # print(f'k_m_пр = {g} = {x_4/x_1}')
    elif i==14:
        x_1 = a * f / (g + 1.0)
        x_4 = a * f * g / (g + 1.0)
        x_5 = a * (b * f - b - d * f + d) / (d * (b + 1.0))
        x_7 = a * b * (1.0 - f) / (d * (b + 1.0))
        x_8 = a * b * (1.0 - f) / (b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_4+x_5+x_7+x_8}')
        # print(f'k_m = {b} = {x_8/(x_5+x_7 )}')
        # print(f'k_m_огг= {d} = {x_8/x_7}')
        # print(f'n%= {f} = {(x_1+x_4)/(x_1+x_4+x_5+x_7+x_8 )}')
        # print(f'k_m_пр = {g} = {x_4/x_1}')
    elif i==15:
        x_1 =a*f/(g + 1.0)
        x_4 =a*f*g/(g + 1.0)
        x_5 =a*(1.0 - f)/(b + 1.0)
        x_6 =a*c*(1.0 - f)/(b + 1.0)
        x_8 =a*(-b*f + b + c*f - c)/(b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_4+x_5+x_6+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/x_5 }')
        # print(f'k_m_вгг= {c} = {x_6/x_5}')
        # print(f'n%= {f} = {(x_1+x_4)/(x_1+x_4+x_5+x_6+x_8 )}')
        # print(f'k_m_пр = {g} = {x_4/x_1}')
    elif i==16:
        x_1 = a * f / (g + 1.0)
        x_4 = a * f * g / (g + 1.0)
        x_5 = a * (-b * f + b + d * f - d) / (b * c - b * d + c - d)
        x_6 = a * c * (-b * f + b + d * f - d) / (b * c - b * d + c - d)
        x_7 = a * (b * f - b - c * f + c) / (b * c - b * d + c - d)
        x_8 = a * d * (b * f - b - c * f + c) / (b * c - b * d + c - d)
        # print(f'm_сум = {a} = {x_1+x_4+x_5+x_6+x_7+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/(x_5+x_7 )}')
        # print(f'k_m_вгг= {c} = {x_6/x_5}')
        # print(f'k_m_огг= {d} = {x_8 / x_7}')
        # print(f'n%= {f} = {(x_1+x_4)/(x_1+x_4+x_5+x_6+x_7+x_8 )}')
        # print(f'k_m_пр = {g} = {x_4/x_1}')
    elif i==17:
        x_1 = a * f * (d - g) / (d * (g + 1.0))
        x_3 = a * f * g / (d * (g + 1.0))
        x_4 = a * f * g / (g + 1.0)
        x_5 = a * (1.0 - f) / (b + 1.0)
        x_8 = a * b * (1.0 - f) / (b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_3+x_4+x_5+x_8}')
        # print(f'k_m = {b} = {x_8/x_5 }')
        # print(f'k_m_огг= {d} = {x_4/x_3 }')
        # print(f'n%= {f} = {(x_1+x_3+x_4)/(x_1+x_3+x_4+x_5+x_8 )}')
        # print(f'k_m_пр = {g} = {x_4/(x_1+x_3 )}')
    elif i==18:
        x_1 = a * f * (d - g) / (d * (g + 1.0))
        x_3 = a * f * g / (d * (g + 1.0))
        x_4 = a * f * g / (g + 1.0)
        x_5 = a * (b * f - b - d * f + d) / (d * (b + 1.0))
        x_7 = a * b * (1.0 - f) / (d * (b + 1.0))
        x_8 = a * b * (1.0 - f) / (b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_3+x_4+x_5+x_7+x_8}')
        # print(f'k_m = {b} = {x_8/(x_5+x_7 )}')
        # print(f'k_m_огг= {d} = {x_4/x_3 }')
        # print(f'k_m_огг= {d} = {x_8/x_7 }')
        # print(f'n%= {f} = {(x_1+x_3+x_4)/(x_1+x_3+x_4+x_5+x_7+x_8 )}')
        # print(f'k_m_пр = {g} = {x_4/(x_1+x_3 )}')
    elif i==19:
        x_1 = a * f * (d - g) / (d * (g + 1.0))
        x_3 = a * f * g / (d * (g + 1.0))
        x_4 = a * f * g / (g + 1.0)
        x_5 = a * (1.0 - f) / (b + 1.0)
        x_6 = a * c * (1.0 - f) / (b + 1.0)
        x_8 = a * (-b * f + b + c * f - c) / (b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_3+x_4+x_5+x_6+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/x_5 }')
        # print(f'k_m_вгг= {c} = {x_6/x_5 }')
        # print(f'k_m_огг= {d} = {x_4/x_3 }')
        # print(f'n%= {f} = {(x_1+x_3+x_4)/(x_1+x_3+x_4+x_5+x_6+x_8 )}')
        # print(f'k_m_пр = {g} = {x_4/(x_1+x_3 )}')
    elif i==20:
        x_1 = a * f * (d - g) / (d * (g + 1.0))
        x_3 = a * f * g / (d * (g + 1.0))
        x_4 = a * f * g / (g + 1.0)
        x_5 = a * (-b * f + b + d * f - d) / (b * c - b * d + c - d)
        x_6 = a * c * (-b * f + b + d * f - d) / (b * c - b * d + c - d)
        x_7 = a * (b * f - b - c * f + c) / (b * c - b * d + c - d)
        x_8 = a * d * (b * f - b - c * f + c) / (b * c - b * d + c - d)
        # print(f'm_сум = {a} = {x_1+x_3+x_4+x_5+x_6+x_7+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/(x_5+x_7)}')
        # print(f'k_m_вгг= {c} = {x_6/x_5}')
        # print(f'k_m_огг= {d} = {x_4/x_3}')
        # print(f'k_m_огг= {d} = {x_8/x_7}')
        # print(f'n%= {f} = {(x_1+x_3+x_4)/(x_1+x_3+x_4+x_5+x_6+x_7+x_8)}')
        # print(f'k_m_пр = {g} = {x_4/(x_1+x_3)}')
    elif i==21:
        x_1 = a * f / (g + 1.0)
        x_2 = a * c * f / (g + 1.0)
        x_4 = a * f * (-c + g) / (g + 1.0)
        x_5 = a * (1.0 - f) / (b + 1.0)
        x_8 = a * b * (1.0 - f) / (b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_2+x_4+x_5+x_8}')
        # print(f'k_m = {b} = {x_8/x_5}')
        # print(f'k_m_вгг= {c} = {x_2/x_1}')
        # print(f'n%= {f} = {(x_1+x_2+x_4)/(x_1+x_2+x_4+x_5+x_8 )}')
        # print(f'k_m_пр = {g} = {(x_2+x_4)/x_1}')
    elif i==22:
        x_1 = a * f / (g + 1.0)
        x_2 = a * c * f / (g + 1.0)
        x_4 = a * f * (-c + g) / (g + 1.0)
        x_5 = a * (b * f - b - d * f + d) / (d * (b + 1.0))
        x_7 = a * b * (1.0 - f) / (d * (b + 1.0))
        x_8 = a * b * (1.0 - f) / (b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_2+x_4+x_5+x_7+x_8}')
        # print(f'k_m = {b} = {x_8/(x_5+x_7 )}')
        # print(f'k_m_вгг= {c} = {x_2/x_1}')
        # print(f'k_m_огг= {d} = {x_8/x_7}')
        # print(f'n%= {f} = {(x_1+x_2+x_4)/(x_1+x_2+x_4+x_5+x_7+x_8 )}')
        # print(f'k_m_пр = {g} = {(x_2+x_4)/x_1}')
    elif i==23:
        x_1 = a * f / (g + 1.0)
        x_2 = a * c * f / (g + 1.0)
        x_4 = a * f * (-c + g) / (g + 1.0)
        x_5 = a * (1.0 - f) / (b + 1.0)
        x_6 = a * c * (1.0 - f) / (b + 1.0)
        x_8 = a * (-b * f + b + c * f - c) / (b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_2+x_4+x_5+x_6+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/x_5}')
        # print(f'k_m_вгг= {c} = {x_2/x_1}')
        # print(f'k_m_вгг= {c} = {x_6/x_5}')
        # print(f'n%= {f} = {(x_1+x_2+x_4)/(x_1+x_2+x_4+x_5+x_6+x_8 )}')
        # print(f'k_m_пр = {g} = {(x_2+x_4)/x_1}')
    elif i==24:
        x_1 = a * f / (g + 1.0)
        x_2 = a * c * f / (g + 1.0)
        x_4 = a * f * (-c + g) / (g + 1.0)
        x_5 = a * (-b * f + b + d * f - d) / (b * c - b * d + c - d)
        x_6 = a * c * (-b * f + b + d * f - d) / (b * c - b * d + c - d)
        x_7 = a * (b * f - b - c * f + c) / (b * c - b * d + c - d)
        x_8 = a * d * (b * f - b - c * f + c) / (b * c - b * d + c - d)
        # print(f'm_сум = {a} = {x_1+x_2+x_4+x_5+x_6+x_7+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/(x_5+x_7)}')
        # print(f'k_m_вгг= {c} = {x_2/x_1}')
        # print(f'k_m_вгг= {c} = {x_6/x_5}')
        # print(f'k_m_огг= {d} = {x_8/x_7}')
        # print(f'n%= {f} = {(x_1+x_2+x_4)/(x_1+x_2+x_4+x_5+x_6+x_7+x_8)}')
        # print(f'k_m_пр = {g} = {(x_2+x_4)/x_1}')
    elif i==25:
        x_1 = a * f * (-d + g) / (c * g + c - d * g - d)
        x_2 = a * c * f * (-d + g) / (c * g + c - d * g - d)
        x_3 = a * f * (c - g) / (c * g + c - d * g - d)
        x_4 = a * d * f * (c - g) / (c * g + c - d * g - d)
        x_5 = a * (1.0 - f) / (b + 1.0)
        x_8 = a * b * (1.0 - f) / (b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_2+x_3+x_4+x_5+x_8}')
        # print(f'k_m = {b} = {x_8/x_5}')
        # print(f'k_m_вгг= {c} = {x_2/x_1}')
        # print(f'k_m_огг= {d} = {x_4/x_3}')
        # print(f'n%= {f} = {(x_1+x_2+x_3+x_4)/(x_1+x_2+x_3+x_4+x_5+x_8 )}')
        # print(f'k_m_пр = {g} = {(x_2+x_4)/(x_1+x_3 )}')
    elif i==26:
        x_1 = a * f * (-d + g) / (c * g + c - d * g - d)
        x_2 = a * c * f * (-d + g) / (c * g + c - d * g - d)
        x_3 = a * f * (c - g) / (c * g + c - d * g - d)
        x_4 = a * d * f * (c - g) / (c * g + c - d * g - d)
        x_5 = a * (b * f - b - d * f + d) / (d * (b + 1.0))
        x_7 = a * b * (1.0 - f) / (d * (b + 1.0))
        x_8 = a * b * (1.0 - f) / (b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_2+x_3+x_4+x_5+x_7+x_8}')
        # print(f'k_m = {b} = {x_8/(x_5+x_7 )}')
        # print(f'k_m_вгг= {c} = {x_2/x_1}')
        # print(f'k_m_огг= {d} = {x_4/x_3}')
        # print(f'k_m_огг= {d} = {x_8/x_7}')
        # print(f'n%= {f} = {(x_1+x_2+x_3+x_4)/(x_1+x_2+x_3+x_4+x_5+x_7+x_8 )}')
        # print(f'k_m_пр = {g} = {(x_2+x_4)/(x_1+x_3 )}')
    elif i==27:
        x_1 = a * f * (-d + g) / (c * g + c - d * g - d)
        x_2 = a * c * f * (-d + g) / (c * g + c - d * g - d)
        x_3 = a * f * (c - g) / (c * g + c - d * g - d)
        x_4 = a * d * f * (c - g) / (c * g + c - d * g - d)
        x_5 = a * (1.0 - f) / (b + 1.0)
        x_6 = a * c * (1.0 - f) / (b + 1.0)
        x_8 = a * (-b * f + b + c * f - c) / (b + 1.0)
        # print(f'm_сум = {a} = {x_1+x_2+x_3+x_4+x_5+x_6+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/x_5}')
        # print(f'k_m_вгг= {c} = {x_2/x_1}')
        # print(f'k_m_вгг= {c} = {x_6/x_5}')
        # print(f'k_m_огг= {d} = {x_4/x_3}')
        # print(f'n%= {f} = {(x_1+x_2+x_3+x_4)/(x_1+x_2+x_3+x_4+x_5+x_6+x_8 )}')
        # print(f'k_m_пр = {g} = {(x_2+x_4)/(x_1+x_3 )}')
    elif i==28:
        x_1 = a * f * (-d + g) / (c * g + c - d * g - d)
        x_2 = a * c * f * (-d + g) / (c * g + c - d * g - d)
        x_3 = a * f * (c - g) / (c * g + c - d * g - d)
        x_4 = a * d * f * (c - g) / (c * g + c - d * g - d)
        x_5 = a * (-b * f + b + d * f - d) / (b * c - b * d + c - d)
        x_6 = a * c * (-b * f + b + d * f - d) / (b * c - b * d + c - d)
        x_7 = a * (b * f - b - c * f + c) / (b * c - b * d + c - d)
        x_8 = a * d * (b * f - b - c * f + c) / (b * c - b * d + c - d)
        # print(f'm_сум = {a} = {x_1+x_2+x_3+x_4+x_5+x_6+x_7+x_8}')
        # print(f'k_m = {b} = {(x_6+x_8)/(x_5+x_7 )}')
        # print(f'k_m_вгг= {c} = {x_2/x_1}')
        # print(f'k_m_вгг= {c} = {x_6/x_5}')
        # print(f'k_m_огг= {d} = {x_4/x_3}')
        # print(f'k_m_огг= {d} = {x_8/x_7}')
        # print(f'n%= {f} = {(x_1+x_2+x_3+x_4)/(x_1+x_2+x_3+x_4+x_5+x_6+x_7+x_8 )}')
        # print(f'k_m_пр = {g} = {(x_2+x_4)/(x_1+x_3 )}')
    return x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8
